#!/usr/bin/env python3
"""Stage5 Hard Knowledge Candidate Pool Cleaning & Tiering
Cleans 2993 candidates into 4 tiers based on quality, template detection, and dedup.
Does NOT modify main graph. Does NOT merge."""

import json
import re
from datetime import datetime, timezone
from collections import defaultdict

GRAPH_PATH = "merged_knowledge_graph_item_dependencies_refined.json"
CAND_PATH = "data/stage5_hard_knowledge_candidates.json"
AUDIT_PATH = "data/stage5_hard_knowledge_candidate_audit.json"

OUT_CLEAN = "data/stage5_hard_knowledge_cleaned_candidates.json"
OUT_CORE = "data/stage5_hard_knowledge_ready_core_candidates.json"
OUT_MERGE = "data/stage5_hard_knowledge_merge_or_collapse_candidates.json"
OUT_DEFER = "data/stage5_hard_knowledge_defer_or_drop_candidates.json"
OUT_REPORT = "docs/stage5_hard_knowledge_candidate_cleaning_report.md"

print("=" * 60)
print("Stage5 Hard Knowledge Candidate Cleaning & Tiering")
print("=" * 60)

# ============================================================
# 1. LOAD DATA
# ============================================================
with open(GRAPH_PATH, "r", encoding="utf-8") as f:
    graph = json.load(f)

with open(CAND_PATH, "r", encoding="utf-8") as f:
    candidates = json.load(f)

with open(AUDIT_PATH, "r", encoding="utf-8") as f:
    audit = json.load(f)

# Build graph lookup
name_lower_set = set()
en_lower_set = set()
alias_lower_set = set()
items_by_id = {}

for cat in graph.get("categories", []):
    for sec in cat.get("sections", []):
        for item in sec.get("items", []):
            iid = item["id"]
            items_by_id[iid] = item
            n = item.get("name", "").lower().strip().replace(" ", "")
            en = item.get("en_name", "").lower().strip().replace(" ", "")
            if n: name_lower_set.add(n)
            if en: en_lower_set.add(en)
            for a in item.get("aliases", []):
                alias_lower_set.add(a.lower().strip().replace(" ", ""))
            for ga in item.get("global_aliases", []):
                alias_lower_set.add(ga.lower().strip().replace(" ", ""))

item_count = len(items_by_id)
print(f"  Graph: {item_count} items")
print(f"  Candidates: {len(candidates)}")

def tokenize(s):
    return set(re.sub(r'[^a-z0-9\u4e00-\u9fff]', ' ', s.lower()).split())

def jaccard(a, b):
    ta, tb = tokenize(a), tokenize(b)
    if not ta or not tb: return 0
    return len(ta & tb) / len(ta | tb)

# ============================================================
# 2. DETECT TEMPLATE PATTERNS
# ============================================================
print(f"\n  Detecting template patterns...")

# Known template suffix patterns (generated by automated expansion)
TEMPLATE_SUFFIXES = [
    "状态定义", "状态压缩维度拆分", "转移依赖图", "无后效性判定",
    "边界状态集合", "滚动状态压缩", "状态转移方程", "最优子结构验证",
    "记忆化搜索实现", "空间优化技巧", "时间复杂度分析", "正确性证明",
    "必胜态判定", "SG 函数计算", "异或和性质", "胜负判定",
    "状态转移方程推导", "组合游戏建模", "必败态分析", "策略构造",
    "Mex运算", "SG定理应用", "Nim和判定",
    "查询模型", "信息增益", "最坏情况界", "自适应策略",
    "确定性算法", "随机化算法", "最优查询序列",
    "转移概率", "期望方程", "方差计算", "稳态分布",
    "首达时间", "期望步数", "概率母函数计算",
]

# Known template prefix patterns
TEMPLATE_PREFIXES = [
    "数位 DP", "区间 DP", "背包 DP", "树形 DP", "状压 DP", "概率 DP",
    "计数 DP", "插头 DP", "轮廓线 DP", "换根 DP",
]

# Check for brief templates
BRIEF_TEMPLATES = [
    "是将状态、转移和边界拆成可证明子问题的动态规划知识点",
    "是一种高效处理区间操作与查询的",
    "是一种基于",
    "是利用",
    "是通过",
    "是在",
]

def is_template_candidate(c):
    name = c["name"]
    brief = c.get("brief", "")

    # Check suffix patterns
    for suffix in TEMPLATE_SUFFIXES:
        if name.endswith(suffix):
            return True, f"template_suffix:{suffix}"

    # Check if name has "的 X" pattern where X is a template suffix
    for suffix in TEMPLATE_SUFFIXES:
        if f"的{suffix}" in name:
            return True, f"template_的{suffix}"
        if f" {suffix}" in name:
            return True, f"template_space_{suffix}"

    # Check brief templates
    for bt in BRIEF_TEMPLATES:
        if bt in brief:
            return True, f"brief_template"

    return False, ""

# ============================================================
# 3. DETECT OVER-SPLITTING
# ============================================================
# Group candidates by topic prefix to detect over-splitting
prefix_groups = defaultdict(list)
for c in candidates:
    name = c["name"]
    # Extract topic prefix (before "的" or first space)
    m = re.match(r'^(.+?)(?:的| )', name)
    if m:
        prefix_groups[m.group(1).strip()].append(c["name"])
    else:
        prefix_groups[name.strip()].append(c["name"])

OVER_SPLIT_THRESHOLD = 6  # If a topic has >6 sub-items, likely over-split
over_split_topics = {p for p, names in prefix_groups.items() if len(names) > OVER_SPLIT_THRESHOLD}

print(f"  Template suffixes: {len(TEMPLATE_SUFFIXES)}")
print(f"  Over-split topics (>6 items): {len(over_split_topics)}")

# ============================================================
# 4. CHECK EXISTING GRAPH OVERLAP
# ============================================================
def check_existing_overlap(name, en_name=""):
    nl = name.lower().strip().replace(" ", "")
    if nl in name_lower_set:
        return "exact_name"
    enl = en_name.lower().strip().replace(" ", "") if en_name else ""
    if enl and enl in name_lower_set:
        return "exact_en"
    if enl and enl in en_lower_set:
        return "exact_en_match"
    # Quick similarity
    best_sim = 0
    for iid, item in items_by_id.items():
        sim = max(jaccard(name, item.get("name", "")), jaccard(en_name, item.get("en_name", "")))
        best_sim = max(best_sim, sim)
        if sim >= 0.85:
            return "high_similarity"
    if best_sim >= 0.65:
        return "medium_similarity"
    return "none"

# ============================================================
# 5. CHECK INTRA-POOL SEMANTIC DUPLICATES
# ============================================================
# Group by name tokens to find intra-pool duplicates
name_tokens = defaultdict(list)
for c in candidates:
    tokens = frozenset(tokenize(c["name"]))
    name_tokens[tokens].append(c["name"])

intra_dup_names = set()
for tokens, names in name_tokens.items():
    if len(names) > 1:
        for n in names:
            intra_dup_names.add(n)

# Also check by prefix + subcategory overlap
prefix_subcat = defaultdict(list)
for c in candidates:
    key = (c.get("subcategory", ""), c.get("category", ""))
    prefix_subcat[key].append(c["name"])

# ============================================================
# 6. SCORE AND CLASSIFY EACH CANDIDATE
# ============================================================
print(f"\n  Classifying {len(candidates)} candidates...")

results = []
stats = defaultdict(int)
cat_stats = defaultdict(lambda: defaultdict(int))

for idx, c in enumerate(candidates):
    name = c["name"]
    en_name = c.get("english", "")
    cat = c.get("category", "")
    subcat = c.get("subcategory", "")
    diff = c.get("difficulty", 5)
    brief = c.get("brief", "")
    prereqs = c.get("prerequisites", [])

    # Template check
    is_tpl, tpl_reason = is_template_candidate(c)

    # Over-split check
    is_over_split = False
    for prefix in over_split_topics:
        if name.startswith(prefix):
            is_over_split = True
            break

    # Existing overlap
    overlap = check_existing_overlap(name, en_name)

    # Intra-pool duplicate
    is_intra_dup = name in intra_dup_names

    # Granularity check - is the topic too narrow?
    is_granular = False
    granular_patterns = [
        r".*的(状态定义|转移概率|期望方程|方差计算|边界条件|初始条件|终止条件|空间复杂度|时间复杂度|正确性证明)$",
        r".*(定义|判定|计算|分析|验证|推导|实现|优化|证明)$",
    ]
    for pat in granular_patterns:
        if re.match(pat, name):
            is_granular = True
            break

    # Learning value check
    has_value = True
    low_value_patterns = [
        "复杂度分析", "正确性证明", "时间复杂度", "空间复杂度",
        "状态定义", "边界条件", "初始条件", "终止条件",
    ]
    for p in low_value_patterns:
        if name.endswith(p):
            has_value = False
            break

    # Compute scores
    quality_score = 3  # default
    dup_risk = "low"
    gran_risk = "low"
    tpl_risk = "low"

    # Deduction logic
    deductions = []

    if is_tpl:
        quality_score -= 2
        tpl_risk = "high"
        deductions.append(f"template:{tpl_reason}")
    if is_over_split:
        quality_score -= 1
        gran_risk = "medium" if gran_risk == "low" else gran_risk
        deductions.append("over_split")
    if overlap in ("exact_name", "exact_en", "exact_en_match"):
        quality_score -= 2
        dup_risk = "high"
        deductions.append(f"existing_overlap:{overlap}")
    elif overlap == "high_similarity":
        quality_score -= 1
        dup_risk = "high"
        deductions.append("existing_high_sim")
    elif overlap == "medium_similarity":
        dup_risk = "medium"
        deductions.append("existing_medium_sim")
    if is_intra_dup:
        quality_score -= 1
        dup_risk = "medium" if dup_risk == "low" else dup_risk
        deductions.append("intra_pool_dup")
    if is_granular:
        quality_score -= 1
        gran_risk = "high"
        deductions.append("too_granular")
    if not has_value:
        quality_score -= 1
        deductions.append("low_learning_value")
    if diff >= 9:
        quality_score -= 1
        deductions.append("very_high_difficulty")

    # Bonus for good candidates
    if not is_tpl and not is_over_split and overlap == "none" and has_value:
        quality_score += 1
    if diff in (6, 7) and not is_tpl:
        quality_score += 0

    quality_score = max(1, min(5, quality_score))

    # Decision - 4 tier logic
    # Tier 1: ready_core = high quality, low risk, clear independent value
    # Tier 2: reserve_useful = good but has medium risk, needs review, or minor granularity concern
    # Tier 3: merge_or_collapse = template generated or too granular, should combine
    # Tier 4: defer_or_drop = high dup, low value, or redundant
    decision = "defer_or_drop"

    if is_tpl:
        decision = "merge_or_collapse"
        deductions.append("is_template_auto_merge")
    elif dup_risk == "high":
        decision = "defer_or_drop"
        deductions.append("high_dup_auto_defer")
    elif not has_value:
        decision = "defer_or_drop"
        deductions.append("low_learning_value_auto_defer")
    elif quality_score >= 5 and dup_risk == "low" and gran_risk == "low":
        decision = "ready_core"
    elif quality_score >= 4 and dup_risk == "low" and gran_risk == "low":
        decision = "ready_core"
    elif quality_score >= 3 and dup_risk == "low" and gran_risk == "low" and not is_granular:
        decision = "reserve_useful"
    elif quality_score >= 3 and dup_risk in ("low", "medium") and gran_risk != "high":
        decision = "reserve_useful"
    elif quality_score >= 2 and gran_risk == "high":
        decision = "merge_or_collapse"
    elif quality_score >= 2 and dup_risk in ("low", "medium"):
        decision = "reserve_useful"
    else:
        decision = "defer_or_drop"

    reason = "; ".join(deductions) if deductions else "clean_candidate"
    suggested_action = ""
    if decision == "ready_core":
        suggested_action = "include_in_first_batch_dynamic_precheck"
    elif decision == "reserve_useful":
        suggested_action = "hold_for_second_batch"
    elif decision == "merge_or_collapse":
        suggested_action = "merge_into_parent_concept"
    else:
        suggested_action = "defer_or_remove"

    stats[decision] += 1
    cat_stats[cat][decision] += 1

    results.append({
        "candidate_id": f"cand.{idx+1:04d}",
        "name": name,
        "category": cat,
        "subcategory": subcat,
        "decision": decision,
        "quality_score": quality_score,
        "duplicate_risk": dup_risk,
        "granularity_risk": gran_risk,
        "template_like_risk": tpl_risk,
        "reason": reason,
        "suggested_action": suggested_action,
        "difficulty": diff,
        "existing_overlap": overlap,
        "is_template": is_tpl,
        "is_over_split": is_over_split,
        "is_intra_dup": is_intra_dup
    })

print(f"\n{'=' * 60}")
print(f"  CLASSIFICATION RESULTS")
print(f"{'=' * 60}")
print(f"  ready_core: {stats['ready_core']}")
print(f"  reserve_useful: {stats['reserve_useful']}")
print(f"  merge_or_collapse: {stats['merge_or_collapse']}")
print(f"  defer_or_drop: {stats['defer_or_drop']}")

for cat in ["算法", "数据结构", "数学"]:
    cs = cat_stats[cat]
    print(f"\n  {cat}:")
    for tier in ["ready_core", "reserve_useful", "merge_or_collapse", "defer_or_drop"]:
        print(f"    {tier}: {cs.get(tier, 0)}")

# ============================================================
# 7. OUTPUT FILES
# ============================================================
print(f"\n  Writing outputs...")
ts = datetime.now(timezone.utc).isoformat()

core = [r for r in results if r["decision"] == "ready_core"]
reserve = [r for r in results if r["decision"] == "reserve_useful"]
merge = [r for r in results if r["decision"] == "merge_or_collapse"]
defer = [r for r in results if r["decision"] == "defer_or_drop"]

# Cleaned (all tiers)
cleaned = {
    "meta": {
        "generated_at": ts, "original_count": len(candidates),
        "cleaned_count": len(results),
        "ready_core": len(core), "reserve_useful": len(reserve),
        "merge_or_collapse": len(merge), "defer_or_drop": len(defer),
        "main_graph_modified": False, "merge_executed": False,
        "baseline_item_count": item_count
    },
    "tier_distribution": dict(stats),
    "category_distribution": {cat: dict(cs) for cat, cs in cat_stats.items()},
    "all_classified": results
}
with open(OUT_CLEAN, "w", encoding="utf-8") as f:
    json.dump(cleaned, f, ensure_ascii=False, indent=2)
print(f"    [OK] {OUT_CLEAN}")

# Ready core
with open(OUT_CORE, "w", encoding="utf-8") as f:
    json.dump({
        "meta": {"generated_at": ts, "count": len(core), "tier": "ready_core"},
        "candidates": core
    }, f, ensure_ascii=False, indent=2)
print(f"    [OK] {OUT_CORE}")

# Merge or collapse
with open(OUT_MERGE, "w", encoding="utf-8") as f:
    json.dump({
        "meta": {"generated_at": ts, "count": len(merge), "tier": "merge_or_collapse"},
        "candidates": merge
    }, f, ensure_ascii=False, indent=2)
print(f"    [OK] {OUT_MERGE}")

# Defer or drop
with open(OUT_DEFER, "w", encoding="utf-8") as f:
    json.dump({
        "meta": {"generated_at": ts, "count": len(defer), "tier": "defer_or_drop"},
        "candidates": defer
    }, f, ensure_ascii=False, indent=2)
print(f"    [OK] {OUT_DEFER}")

# Report
total = len(results)
tpl_total = sum(1 for r in results if r["is_template"])
gran_total = sum(1 for r in results if r["granularity_risk"] == "high")
dup_high = sum(1 for r in results if r["duplicate_risk"] == "high")
dup_med = sum(1 for r in results if r["duplicate_risk"] == "medium")

# Subcategory breakdown for ready_core
rc_subcat = defaultdict(int)
for r in core:
    rc_subcat[r["subcategory"]] += 1

# Quality score distribution
qs_dist = defaultdict(int)
for r in results:
    qs_dist[r["quality_score"]] += 1

with open(OUT_REPORT, "w", encoding="utf-8") as f:
    f.write("# Stage5 硬知识候选池清洗分层报告\n\n")
    f.write(f"**生成时间**: {ts}\n\n")
    f.write(f"**基线**: {item_count} 个已有知识点\n\n")

    f.write("## 1. 原始候选总数\n\n**2993**\n\n")

    f.write("## 2. ready_core 数量\n\n")
    f.write(f"**{len(core)}** — 高质量、低重复、独立学习价值明确\n\n")
    f.write("| 分类 | 数量 |\n|------|------|\n")
    for cat in ["算法", "数据结构", "数学"]:
        cs = cat_stats[cat]
        f.write(f"| {cat} | {cs.get('ready_core', 0)} |\n")

    f.write(f"\n## 3. reserve_useful 数量\n\n")
    f.write(f"**{len(reserve)}** — 有价值但需后续再筛\n\n")
    f.write("| 分类 | 数量 |\n|------|------|\n")
    for cat in ["算法", "数据结构", "数学"]:
        cs = cat_stats[cat]
        f.write(f"| {cat} | {cs.get('reserve_useful', 0)} |\n")

    f.write(f"\n## 4. merge_or_collapse 数量\n\n")
    f.write(f"**{len(merge)}** — 有价值但颗粒度过细，建议合并\n\n")

    f.write(f"\n## 5. defer_or_drop 数量\n\n")
    f.write(f"**{len(defer)}** — 重复、泛化、价值不清\n\n")

    f.write("## 6. 算法/数据结构/数学分别保留情况\n\n")
    f.write("| 分类 | ready_core | reserve_useful | merge_or_collapse | defer_or_drop | 总计 |\n")
    f.write("|------|-----------|---------------|-------------------|--------------|------|\n")
    for cat in ["算法", "数据结构", "数学"]:
        cs = cat_stats[cat]
        t = sum(cs.values())
        f.write(f"| {cat} | {cs.get('ready_core',0)} | {cs.get('reserve_useful',0)} | {cs.get('merge_or_collapse',0)} | {cs.get('defer_or_drop',0)} | {t} |\n")

    f.write(f"\n## 7. 模板化候选风险分析\n\n")
    f.write(f"| 指标 | 值 |\n|------|-----|\n")
    f.write(f"| 模板化候选总数 | {tpl_total} ({tpl_total/total*100:.1f}%) |\n")
    f.write(f"| 过度拆分主题数 | {len(over_split_topics)} |\n")
    f.write(f"| 高颗粒度候选 | {gran_total} |\n\n")
    f.write(f"**典型模板模式**:\n\n")
    f.write(f"- 'X 的 状态定义/转移概率/期望方程/...' — 每个主题被自动展开为 6-12 个子知识点\n")
    f.write(f"- 250 个 DP 候选使用同一 brief 模板\n")
    f.write(f"- 博弈论 132 个候选中大部分为 'X 的 必胜态判定/SG计算/异或和' 模式\n")
    f.write(f"- 交互题 110 个候选中大部分为 'X 的 查询模型/信息增益/最坏情况界' 模式\n")
    f.write(f"- **建议**: 将模板化候选合并为父主题概念节点\n\n")

    f.write(f"## 8. 过度拆分风险分析\n\n")
    f.write(f"| 指标 | 值 |\n|------|-----|\n")
    f.write(f"| 超过 {OVER_SPLIT_THRESHOLD} 个子项的主题数 | {len(over_split_topics)} |\n")
    f.write(f"| 高颗粒度候选 | {gran_total} |\n")
    f.write(f"| 典型拆分模式 | 每个主题 → 10-12 个子知识点 |\n\n")
    f.write(f"**建议合并策略**:\n\n")
    f.write(f"- 每个主题合并为 1 个核心概念 + 1-2 个实现变体\n")
    f.write(f"- 372 个模板化候选预计合并为 ~60-80 个正式节点\n\n")

    f.write(f"## 9. 建议第一批动态预审数量\n\n")
    f.write(f"**{len(core)}** (ready_core 层级)\n\n")
    f.write(f"ready_core 子类分布:\n\n")
    f.write("| 子类 | 数量 |\n|------|------|\n")
    for sc, cnt in sorted(rc_subcat.items(), key=lambda x: -x[1]):
        f.write(f"| {sc} | {cnt} |\n")

    f.write(f"\n## 10. 是否建议直接合并\n\n**否** — 必须先做动态预审和依赖映射。\n\n")
    f.write(f"## 11. 是否修改主图谱\n\n**否**\n\n")

    f.write(f"## 12. 质量分分布\n\n")
    f.write("| 分数 | 数量 |\n|------|------|\n")
    for qs in sorted(qs_dist.keys()):
        f.write(f"| {qs} | {qs_dist[qs]} |\n")

    f.write(f"\n## 13. 重复风险分布\n\n")
    f.write(f"| 风险级别 | 数量 |\n|---------|------|\n")
    f.write(f"| high | {dup_high} |\n")
    f.write(f"| medium | {dup_med} |\n")
    f.write(f"| low | {total - dup_high - dup_med} |\n\n")

    f.write(f"## 14. 后续建议\n\n")
    f.write(f"1. **第一批**: 优先处理 ready_core ({len(core)} 个)，做动态预审和依赖映射\n")
    f.write(f"2. **第二批**: reserve_useful ({len(reserve)} 个) 需人工审核后再决定\n")
    f.write(f"3. **合并处理**: merge_or_collapse ({len(merge)} 个) 先合并为更大节点再入池\n")
    f.write(f"4. **暂缓**: defer_or_drop ({len(defer)} 个) 暂缓或丢弃\n")
    f.write(f"5. **预计最终有效节点**: ~{len(core) + len(reserve)//3 + 70} 个（ready_core + 1/3 reserve + 合并后模板）\n\n")
    f.write(f"---\n*本报告自动生成*\n")

print(f"    [OK] {OUT_REPORT}")

print(f"\n{'=' * 60}")
print(f"  Cleaning Complete")
print(f"{'=' * 60}")
print(f"  ready_core: {len(core)}")
print(f"  reserve_useful: {len(reserve)}")
print(f"  merge_or_collapse: {len(merge)}")
print(f"  defer_or_drop: {len(defer)}")
print(f"  Total: {len(results)}")
print(f"  No graph modifications.")
